export enum RouterPage {
  LOGIN = 'login',
  REGISTER = 'register',
  LOGOUT = 'logout',
  HOME = 'home',
  ACCOUNT = 'account',
  BUDGET = 'budget',
  ONBOARDING = 'onboarding',
  BUDGET_CREATE = 'budgetCreate',
  SETTINGS = 'settings',
  SETTINGS_SETTINGS = 'settingsSettings',
  SETTINGS_PROFILE = 'settingsProfile',
  SETTINGS_CHANGE_PASSWORD = 'settingsChangePassword',
  SETTINGS_ACCOUNTS = 'settingsAccounts',
  SETTINGS_CATEGORIES = 'settingsCategories',
  SETTINGS_PAYEES = 'settingsPayees',
  SETTINGS_TAGS = 'settingsTags',
  SETTINGS_CONNECTIONS = 'settingsConnections',
   SETTINGS_BUDGETS = 'settingsBudgets',
  RECURRING_TRANSACTIONS = 'recurringTransactions',
}
